// @generated
mod props;
/// This data provider was programmatically generated by [`icu_datagen`](
/// https://unicode-org.github.io/icu4x-docs/doc/icu_datagen/enum.Out.html#variant.Module).
#[non_exhaustive]
pub struct BakedDataProvider;
use ::icu_provider::prelude::*;
#[cfg(feature = "icu_properties")]
impl DataProvider<::icu_properties::provider::EmojiComponentV1Marker> for BakedDataProvider {
    fn load(&self, req: DataRequest) -> Result<DataResponse<::icu_properties::provider::EmojiComponentV1Marker>, DataError> {
        Ok(DataResponse {
            metadata: Default::default(),
            payload: Some(DataPayload::from_owned(zerofrom::ZeroFrom::zero_from(
                *props::ecomp_v1::DATA
                    .get_by(|k| req.locale.strict_cmp(k.as_bytes()).reverse())
                    .ok_or_else(|| DataErrorKind::MissingLocale.with_req(::icu_properties::provider::EmojiComponentV1Marker::KEY, req))?,
            ))),
        })
    }
}
#[cfg(feature = "icu_properties")]
impl DataProvider<::icu_properties::provider::EmojiModifierBaseV1Marker> for BakedDataProvider {
    fn load(&self, req: DataRequest) -> Result<DataResponse<::icu_properties::provider::EmojiModifierBaseV1Marker>, DataError> {
        Ok(DataResponse {
            metadata: Default::default(),
            payload: Some(DataPayload::from_owned(zerofrom::ZeroFrom::zero_from(
                *props::ebase_v1::DATA
                    .get_by(|k| req.locale.strict_cmp(k.as_bytes()).reverse())
                    .ok_or_else(|| DataErrorKind::MissingLocale.with_req(::icu_properties::provider::EmojiModifierBaseV1Marker::KEY, req))?,
            ))),
        })
    }
}
#[cfg(feature = "icu_properties")]
impl DataProvider<::icu_properties::provider::EmojiModifierV1Marker> for BakedDataProvider {
    fn load(&self, req: DataRequest) -> Result<DataResponse<::icu_properties::provider::EmojiModifierV1Marker>, DataError> {
        Ok(DataResponse {
            metadata: Default::default(),
            payload: Some(DataPayload::from_owned(zerofrom::ZeroFrom::zero_from(
                *props::emod_v1::DATA
                    .get_by(|k| req.locale.strict_cmp(k.as_bytes()).reverse())
                    .ok_or_else(|| DataErrorKind::MissingLocale.with_req(::icu_properties::provider::EmojiModifierV1Marker::KEY, req))?,
            ))),
        })
    }
}
#[cfg(feature = "icu_properties")]
impl DataProvider<::icu_properties::provider::EmojiPresentationV1Marker> for BakedDataProvider {
    fn load(&self, req: DataRequest) -> Result<DataResponse<::icu_properties::provider::EmojiPresentationV1Marker>, DataError> {
        Ok(DataResponse {
            metadata: Default::default(),
            payload: Some(DataPayload::from_owned(zerofrom::ZeroFrom::zero_from(
                *props::epres_v1::DATA
                    .get_by(|k| req.locale.strict_cmp(k.as_bytes()).reverse())
                    .ok_or_else(|| DataErrorKind::MissingLocale.with_req(::icu_properties::provider::EmojiPresentationV1Marker::KEY, req))?,
            ))),
        })
    }
}
#[cfg(feature = "icu_properties")]
impl DataProvider<::icu_properties::provider::EmojiV1Marker> for BakedDataProvider {
    fn load(&self, req: DataRequest) -> Result<DataResponse<::icu_properties::provider::EmojiV1Marker>, DataError> {
        Ok(DataResponse {
            metadata: Default::default(),
            payload: Some(DataPayload::from_owned(zerofrom::ZeroFrom::zero_from(
                *props::emoji_v1::DATA
                    .get_by(|k| req.locale.strict_cmp(k.as_bytes()).reverse())
                    .ok_or_else(|| DataErrorKind::MissingLocale.with_req(::icu_properties::provider::EmojiV1Marker::KEY, req))?,
            ))),
        })
    }
}
